# Generated by Django 5.2 on 2025-05-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='useer_type',
            new_name='user_type',
        ),
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(default='Password123', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='Password123', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='Password123', max_length=100),
        ),
    ]
