# Generated by Django 5.2 on 2025-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('alumni', 'Alumni'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10, null=True),
        ),
    ]
