# Generated by Django 5.2 on 2025-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0019_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isNotified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isNotify',
            field=models.BooleanField(default=False),
        ),
    ]
