# Generated by Django 5.2 on 2025-06-01 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0020_event_isnotified_event_isnotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='notified_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
