# Generated by Django 5.2 on 2025-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0022_remove_event_isnotified_remove_event_isnotify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
