# Generated by Django 5.2 on 2025-06-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0025_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
