# Generated by Django 5.2 on 2025-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0026_delete_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
