# Generated by Django 5.2 on 2025-07-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0028_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at']},
        ),
    ]
