# Generated by Django 5.2 on 2025-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Chat', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_sen',
            field=models.BooleanField(default=False),
        ),
    ]
