# Generated by Django 5.2 on 2025-07-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Chat', '0003_messages_is_sen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='is_sen',
            new_name='is_seen',
        ),
    ]
