# Generated by Django 5.2 on 2025-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='graduation_year',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10, null=True),
        ),
    ]
