# Generated by Django 5.2 on 2025-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0010_customuser_address_customuser_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
