# Generated by Django 5.2 on 2025-05-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0014_alter_alumni_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alumni_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
